// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIToolFinderApp.Migrations
{
    [DbContext(typeof(AIToolDbContext))]
    partial class AIToolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AITool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Category")
<<<<<<< HEAD
                        .IsRequired()
=======
>>>>>>> 0c30f6ee7296d1dbdc60a398043d4cd93a150334
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PricingType")
                        .HasColumnType("int");

                    b.Property<string>("ToolName")
<<<<<<< HEAD
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseCase")
=======
>>>>>>> 0c30f6ee7296d1dbdc60a398043d4cd93a150334
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AITools");
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

<<<<<<< HEAD
                    b.Property<int>("AIToolId")
                        .HasColumnType("int");

=======
>>>>>>> 0c30f6ee7296d1dbdc60a398043d4cd93a150334
                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

<<<<<<< HEAD
                    b.HasIndex("AIToolId");

                    b.ToTable("Review");
=======
                    b.HasIndex("ToolId");

                    b.ToTable("Reviews");
>>>>>>> 0c30f6ee7296d1dbdc60a398043d4cd93a150334
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.HasOne("AITool", "AITool")
                        .WithMany("Reviews")
<<<<<<< HEAD
                        .HasForeignKey("AIToolId")
=======
                        .HasForeignKey("ToolId")
>>>>>>> 0c30f6ee7296d1dbdc60a398043d4cd93a150334
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AITool");
                });

            modelBuilder.Entity("AITool", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
